class CouriersType{
    elements = {
        searchType: () => cy.get('.focus-within\\:ring-2 > .bg-white > .flex > .flex-1'),
        addType: () => cy.get('.button'),
        itemsLimit: () => cy.get('.ml-2'),
        nextPage: () => cy.get('.MuiPagination-ul > :nth-child(3)'),
        previousPage: () => cy.get('.MuiPagination-ul > :nth-child(1)'),
        actions: () => cy.get(':nth-child(1) > :nth-child(5) > .ActionMenu > .MuiButtonBase-root > .MuiButton-label > .MuiSvgIcon-root'),
        actionsEdit: () => cy.get('#simple-menu > .MuiPaper-root > .MuiList-root > [tabindex="0"]'),
        actionsDelete: () => cy.get('.MuiList-root > [tabindex="-1"]'),
        modifyTable: () => cy.get('.transition-all > .fill-current > .MuiSvgIcon-root'),
        // for new courier type
        nameField: () => cy.get('#name'),
        fromDistance: () => cy.get('#distance_from'),
        toDistance: () => cy.get('#distance_to'), 
        mondayFromTime: () => cy.get(':nth-child(1) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        mondayToTime: () => cy.get(':nth-child(1) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        mondayStatus: () => cy.get(':nth-child(1) > :nth-child(4) > .rc-switch'),
        tuesdayFromTime: () => cy.get(':nth-child(2) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        tuesdayToTime: () => cy.get(':nth-child(2) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        tuesdayStatus: () => cy.get(':nth-child(2) > :nth-child(4) > .rc-switch'),
        wednesdayFromTime: () =>  cy.get(':nth-child(3) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        wednesdayToTime: () => cy.get(':nth-child(3) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        wednesdayStatus: () =>cy.get(':nth-child(3) > :nth-child(4) > .rc-switch'),
        thursdayFromTime: () => cy.get(':nth-child(4) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        thursdayToTime: () => cy.get(':nth-child(4) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        thursdayStatus: () => cy.get(':nth-child(4) > :nth-child(4) > .rc-switch'), 
        fridayFromTime: () => cy.get(':nth-child(5) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        fridayToTime: () => cy.get(':nth-child(5) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        fridayStatus: () => cy.get(':nth-child(5) > :nth-child(4) > .rc-switch'), 
        saturdayFromTime: () => cy.get(':nth-child(6) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        saturdayToTime: () => cy.get(':nth-child(6) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        saturdayStatus: () => cy.get(':nth-child(6) > :nth-child(4) > .rc-switch'),
        sundayFromTime: () => cy.get(':nth-child(7) > :nth-child(2) > div > .rc-time-picker > .rc-time-picker-input'),
        sundayToTime: () => cy.get(':nth-child(7) > :nth-child(3) > div > .rc-time-picker > .rc-time-picker-input'),
        sundayStatus: () => cy.get(':nth-child(7) > :nth-child(4) > .rc-switch'),   
        saveButton: () => cy.get(':nth-child(2) > .button'),
        cancelButton: () => cy.get(':nth-child(1) > .button')
    }
}